# Generated by Django 2.1.2 on 2018-10-24 02:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('ws84_x', models.FloatField()),
                ('ws84_y', models.FloatField()),
                ('address', models.TextField()),
                ('note', models.TextField()),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='BucketRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bucket_id', models.TextField()),
                ('investigate_date', models.DateField()),
                ('county', models.TextField()),
                ('town', models.TextField()),
                ('village', models.TextField()),
                ('egg_count', models.IntegerField(default=0)),
                ('egypt_egg_count', models.IntegerField(default=0)),
                ('white_egg_count', models.IntegerField(default=0)),
                ('larvae_count', models.IntegerField(default=0)),
                ('egypt_larvae_count', models.IntegerField(default=0)),
                ('white_larvae_count', models.IntegerField(default=0)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BucketStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigate_date', models.DateField()),
                ('county', models.TextField()),
                ('town', models.TextField()),
                ('village', models.TextField()),
                ('total_egg_count', models.IntegerField(default=0)),
                ('positive_rate', models.FloatField(default=0)),
                ('avg_egg_count', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DengueBucket',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('ws84_x', models.FloatField()),
                ('ws84_y', models.FloatField()),
                ('address', models.TextField()),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('investigate_date', models.DateField()),
                ('county', models.TextField()),
                ('town', models.TextField()),
                ('village', models.TextField()),
                ('egg_count', models.IntegerField(default=0)),
                ('egypt_egg_count', models.IntegerField(default=0)),
                ('white_egg_count', models.IntegerField(default=0)),
                ('larvae_count', models.IntegerField(default=0)),
                ('egypt_larvae_count', models.IntegerField(default=0)),
                ('white_larvae_count', models.IntegerField(default=0)),
                ('note', models.TextField()),
            ],
        ),
    ]
