# Generated by Django 2.1.2 on 2018-12-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denguebucket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='id',
            field=models.TextField(db_index=True, default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bucketrecord',
            name='investigate_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='denguebucket',
            name='investigate_date',
            field=models.DateField(db_index=True),
        ),
    ]
