# Generated by Django 2.1.2 on 2018-12-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denguebucket', '0002_auto_20181216_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketrecord',
            name='investigate_date',
            field=models.DateField(),
        ),
    ]
