# Generated by Django 2.1.2 on 2018-12-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denguebucket', '0003_auto_20181216_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketrecord',
            name='investigate_date',
            field=models.DateField(db_index=True),
        ),
    ]
