# Generated by Django 2.1.2 on 2018-10-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BucketStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigate_date', models.DateField()),
                ('county', models.TextField()),
                ('town', models.TextField()),
                ('village', models.TextField()),
                ('total_egg_count', models.IntegerField(default=0)),
                ('positive_rate', models.FloatField(default=0)),
                ('avg_egg_count', models.FloatField(default=0)),
            ],
        ),
    ]
